<?php
declare(strict_types=1);

use Hyva\ReactCheckout\ViewModel\CheckoutConfigProvider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var CheckoutConfigProvider $configProvider */
$configProvider = $block->getData('checkout_config_provider');
?>
<div
    id="react-checkout"
    data-base_url="<?= $block->getBaseUrl() ?>"
    data-static_file_path="<?= $block->getViewFileUrl('Hyva_ReactCheckout') ?>"
    data-checkout_config="<?= $escaper->escapeHtmlAttr($configProvider->getConfig()) ?>"
>
    <div class="container">
        <div class="flex flex-col max-h-screen my-6 lg:flex-row">
            <div class="w-full lg:w-3/5 md:mr-2">
                <div class="mr-1 space-y-2">
                    <div class="w-full px-4 py-4 card">
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="w-full px-4 py-4 card">
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="w-full px-4 py-4 card">
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="sticky self-start w-full lg:w-2/5">
                <div class="ml-1 space-y-2">
                    <div class="w-full px-4 py-4 card">
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="w-full px-4 py-4 card">
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
