<?php
declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Checkout\ViewModel\LocaleProvider $localeProvider */
/** @var \Hyva\Checkout\ViewModel\CheckoutConfigProvider $configProvider */
$localeProvider = $block->getLocaleProvider();
$configProvider = $block->getCheckoutConfigProvider();
?>
<div
    id="react-checkout"
    data-language="<?= $localeProvider->getLocaleCode() ?>"
    data-static_file_path="<?= $block->getViewFileUrl('Hyva_Checkout/js') ?>"
    data-payment="<?= $escaper->escapeHtmlAttr($configProvider->getConfig()) ?>"
>
    <div class="container">
        <div class="flex flex-col max-h-screen mx-2 my-6 overflow-hidden md:mx-12 md:flex-row">
            <div class="md:w-1/4">
                <div class="mr-1 space-y-2">
                    <div class="card w-full px-4 py-4 bg-container-darker overflow-hidden">
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card w-full px-4 py-4 bg-container-darker overflow-hidden">
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card w-full px-4 py-4 bg-container-darker overflow-hidden">
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="md:w-2/4">
                <div class="mx-1 space-y-2">
                    <div class="card w-full px-4 py-4 bg-container-darker overflow-hidden">
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card w-full px-4 py-4 bg-container-darker overflow-hidden">
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card w-full px-4 py-4 bg-container-darker overflow-hidden">
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="flex-grow">
                <div class="ml-1 space-y-2">
                    <div class="card w-full px-4 py-4 bg-container-darker overflow-hidden">
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card w-full px-4 py-4 bg-container-darker overflow-hidden">
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                        <div class="flex space-x-4 animate-pulse">
                            <div class="w-12 h-12 bg-gray-400 rounded-full"></div>
                            <div class="flex-1 py-1 space-y-4">
                                <div class="w-3/4 h-4 bg-gray-400 rounded"></div>
                                <div class="space-y-2">
                                    <div class="h-4 bg-gray-400 rounded"></div>
                                    <div class="w-5/6 h-4 bg-gray-400 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

