<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

?>
<script>
    function loadReactCartScript () {
        var scriptTag = 'script';
        var firstScript = document.getElementsByTagName(scriptTag)[0];
        var newScript = document.createElement(scriptTag);

        newScript.async = true;
        newScript.defer = true;
        newScript.type = 'module';
        newScript.src = '<?= $escaper->escapeUrl($block->getViewFileUrl('Hyva_Checkout::react-checkout.es.js')); ?>';

        firstScript.parentNode.insertBefore(newScript, firstScript);
    }
    window.addEventListener("private-content-loaded", loadReactCartScript);
</script>
