<?php
declare(strict_types=1);

use Hyva\ReactCheckout\ViewModel\CspNonceProvider;
use Magento\Framework\Escaper;
use Hyva\ReactCheckout\Block\CheckoutTranslator;

/**
 * @var CheckoutTranslator $block
 * @var Escaper $escaper
 * @var CspNonceProvider $cspNonceProvider
 */
$cspNonceProvider = $block->getData('csp_nonce_provider');
?>
<script nonce="<?= $escaper->escapeHtml($cspNonceProvider->getNonce()) ?>">
    var CHECKOUT_TRANSLATIONS = '<?= $escaper->escapeJs($block->getTranslations())  ?>';
</script>
