<?php
declare(strict_types=1);

use Hyva\ReactCheckout\ViewModel\CspNonceProvider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var CspNonceProvider $cspNonceProvider */

$cspNonceProvider = $block->getData('csp_nonce_provider');
$buildJsFile = 'Hyva_ReactCheckout::js/react-checkout.js';
?>
<script nonce="<?= $escaper->escapeHtml($cspNonceProvider->getNonce()) ?>">
    function loadReactCartScript () {
        var scriptTag = 'script';
        var firstScript = document.getElementsByTagName(scriptTag)[0];
        var newScript = document.createElement(scriptTag);

        newScript.async = true;
        newScript.defer = true;
        newScript.src = '<?= $escaper->escapeUrl($block->getViewFileUrl($buildJsFile)); ?>';

        firstScript.parentNode.insertBefore(newScript, firstScript);
    }

    if (document.readyState === 'complete') {
        loadReactCartScript();
    } else {
        document.addEventListener("DOMContentLoaded", loadReactCartScript);
    }
</script>
