<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
?>
<div class="flex justify-center mt-2">
    <div class="container">
        <div class="container flex flex-col md:flex-row flex-wrap my-6 font-bold lg:mt-8 text-3xl">
            <h1 class="text-gray-900 page-title title-font">
                    <span class="base" data-ui-id="page-title-wrapper">
                        <?= /* @noEscape */ __('Checkout') ?>
                    </span>
            </h1>
        </div>
    </div>
</div>
