const fs = require('fs');
const util = require('./utility');

const shippingDirectoryPath = './src/shippingMethods/';

/**
 * Setting up custom shipping methods into the react app section
 *
 * This will clone the shipping methods repository specified under
 * `config.shippingMethodsRepo` section in package.json file into the
 * `src/shippingMethods`
 *
 * It will also populate `src/shippingMethods/customRenderers.js` which can be
 * used to port custom shipping renderers into the react app.
 */
const configureShippingMethods = async () => {
  const shippingRepos = util.collectConfiguredReposFromEnv(
    'shippingMethodsRepo'
  );
  const shippingMethodList = Object.keys(shippingRepos);

  await util.cloneAndConfigureRepos(
    shippingRepos,
    shippingDirectoryPath,
    'shipping method'
  );

  if (shippingMethodList.length) {
    let content = `/**
 * 📢 📢 📢 This file is autogenerated and may be overwritten. Handle with care. 🙅🏽 🙅🏽 🙅🏽
 *
 * When you have custom shipping repo integration, then the content of this file
 * will be overwritten during performing "npm install". So, in most of the cases,
 * you don't need to alter the content of this file.
 *
 * But, if you have your own custom shipping methods locally, then you need to
 * include them here as well. That is the only time you need to touch this file.
 */\n\n`;
    content += shippingMethodList
      .map(
        (method) => `import ${method}Renderers from './${method}/renderers';\n`
      )
      .join('');
    content += '\n';
    content += `export default {\n`;
    content += shippingMethodList
      .map((method) => `  ...${method}Renderers,\n`)
      .join('');
    content += '};\n';

    fs.writeFileSync(`${shippingDirectoryPath}customRenderers.js`, content);
  }

  console.log('Shipping methods successfully added');
};

module.exports = configureShippingMethods;
