<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
/**
 * @var \Magento\Theme\ViewModel\Block\Html\Header\LogoSizeResolverInterface|null $logoSizeResolver
 */
$logoSizeResolver = $block->getLogoSizeResolver();
$logoWidth = $logoSizeResolver !== null && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver !== null && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();
?>
<div class="flex justify-center mt-6">
    <div class="container">
        <a
            class="logo"
            href="<?= $block->escapeUrl($block->getUrl('')) ?>"
            title="<?= $block->escapeHtmlAttr($storeName) ?>"
            aria-label="store logo">
            <img src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
                 title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
                 alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
                <?= $logoWidth ? 'width="' . $block->escapeHtmlAttr($logoWidth) . '"' : '' ?>
                <?= $logoHeight ? 'height="' . $block->escapeHtmlAttr($logoHeight) . '"' : '' ?>
            />
        </a>
    </div>
</div>

